language: python

python:
  - "2.6"

env:
  - TOXENV=py26-1.3,py26-1.4,py26-1.5
  - TOXENV=py27-1.3,py27-1.4,py27-1.5
  - TOXENV=docs
  - TOXENV=py26-dev,py27-dev

matrix:
  allow_failures:
    - env: TOXENV=py26-dev,py27-dev

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo cp /etc/postgresql/9.1/main/pg_hba.conf ./
  - sudo apt-get remove postgresql postgresql-9.1 -qq --purge
  - source /etc/lsb-release
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ $DISTRIB_CODENAME-pgdg main" > pgdg.list
  - sudo mv pgdg.list /etc/apt/sources.list.d/
  - wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install postgresql-9.2 postgresql-contrib-9.2 -qq
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew"  install postgresql-server-dev-9.2 postgresql-plpython-9.2 libjson0-dev libarmadillo-dev libpoppler-dev libepsilon-dev libmaloc-dev liblzma-dev
  - sudo /etc/init.d/postgresql stop
  - sudo cp ./pg_hba.conf /etc/postgresql/9.2/main
  - sudo apt-get install postgresql-9.2-postgis
  - sudo /etc/init.d/postgresql start

# command to install dependencies
install:
    - pip install tox

# command to run tests
script:
    - tox
