language: python

python:
  - "2.6"

env:
  - TOXENV=py26-1.3,py26-1.4,py26-1.5
  - TOXENV=py27-1.3,py27-1.4,py27-1.5
  - TOXENV=docs
  - TOXENV=py26-dev,py27-dev

matrix:
  allow_failures:
    - env: TOXENV=py26-dev,py27-dev

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get install postgis
  - sudo /etc/init.d/postgresql start

# command to install dependencies
install:
    - pip install tox

# command to run tests
script:
    - tox
